name       : filelight
version    : 19.12.3
release    : 23
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/filelight-19.12.3.tar.xz : 9ea78509f932cd2bd553d934e2af75c25d0b65d85d2b0ab4a007ac5929b2d3b5
homepage   : https://kde.org/applications/utilities/org.kde.filelight
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical representation of your filesystem
description: |
    Filelight allows you to quickly understand exactly where your diskspace is being used by graphically representing your file system.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
