name       : filelight
version    : 19.08.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/filelight-19.08.3.tar.xz : 95fa38574292a2aa8d3d90749fbbb61c5005889ef1df1aaa04d2d789bbf4fb00
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical representation of your filesystem
description: |
    Filelight allows you to quickly understand exactly where your diskspace is being used by graphically representing your file system.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
