name       : filelight
version    : 19.08.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/filelight-19.08.0.tar.xz : bdd3d32f6666b3d2fa4c614f5f058571c8849484e1ba17a97996680503f8e8e6
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical representation of your filesystem
description: |
    Filelight allows you to quickly understand exactly where your diskspace is being used by graphically representing your file system.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
