name       : filelight
version    : 18.04.2
release    : 1
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/filelight-18.04.2.tar.xz : c2bf1b4f529d38d4a8885217377771052b5a46502ad411dabf1b3f42b9fb1cc4
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical representation of your filesystem
description: |
    Filelight allows you to quickly understand exactly where your diskspace is being used by graphically representing your file system.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
