name       : filelight
version    : 18.04.3
release    : 2
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/filelight-18.04.3.tar.xz : b6fa3cf413bd3e461cba23233aa942ae48dbcf111a9426b3422b9b7f4dd402d4
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde
summary    : Graphical representation of your filesystem
description: |
    Filelight allows you to quickly understand exactly where your diskspace is being used by graphically representing your file system.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
